version: '2'

services:
  app:
    image: atm-system:latest
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:jdbc:postgresql://db:5432/atmdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresdb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=some-postgres
      - POSTGRES_PASSWORD=mysecretpassword